package su.nightexpress.excellentcrates.keys.item.editor.ui.dialog;

import java.util.ArrayList;
import java.util.List;

import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.jspecify.annotations.NullMarked;

import su.nightexpress.excellentcrates.api.key.editor.KeyEditorHook;
import su.nightexpress.excellentcrates.core.SharedPlaceholders;
import su.nightexpress.excellentcrates.core.lang.Lang;
import su.nightexpress.excellentcrates.keys.item.editor.ui.KeyItemEditorUIController;
import su.nightexpress.excellentcrates.keys.item.editor.ui.context.KeyItemDialogContext;
import su.nightexpress.excellentcrates.keys.item.editor.ui.context.KeyItemSetupContext;
import su.nightexpress.excellentcrates.keys.item.lang.KeyItemLang;
import su.nightexpress.excellentcrates.util.ItemHelper;
import su.nightexpress.nightcore.bridge.dialog.wrap.WrappedDialog;
import su.nightexpress.nightcore.bridge.dialog.wrap.body.WrappedDialogBody;
import su.nightexpress.nightcore.bridge.dialog.wrap.input.WrappedDialogInput;
import su.nightexpress.nightcore.bridge.dialog.wrap.input.single.WrappedSingleOptionEntry;
import su.nightexpress.nightcore.bridge.item.AdaptedItem;
import su.nightexpress.nightcore.integration.item.ItemBridge;
import su.nightexpress.nightcore.integration.item.ItemProvider;
import su.nightexpress.nightcore.ui.dialog.Dialogs;
import su.nightexpress.nightcore.ui.dialog.build.DialogActions;
import su.nightexpress.nightcore.ui.dialog.build.DialogBases;
import su.nightexpress.nightcore.ui.dialog.build.DialogBodies;
import su.nightexpress.nightcore.ui.dialog.build.DialogButtons;
import su.nightexpress.nightcore.ui.dialog.build.DialogInputs;
import su.nightexpress.nightcore.ui.dialog.build.DialogTypes;
import su.nightexpress.nightcore.ui.dialog.wrap.Dialog;
import su.nightexpress.nightcore.util.placeholder.PlaceholderContext;

@NullMarked
public class KeyItemStackDialog extends Dialog<KeyItemDialogContext> {

    private static final String KEY_USE_REF          = "use_ref";
    private static final String KEY_USE_NBT          = "use_nbt";
    private static final String KEY_SAVE_METHOD      = "save_method";
    private static final String KEY_SET_DISPLAY_NAME = "set_display_name";
    private static final String KEY_SET_DISPLAY_LORE = "set_display_lore";

    private final KeyItemEditorUIController controller;

    public KeyItemStackDialog(KeyItemEditorUIController controller) {
        super();
        this.controller = controller;
    }

    @Override
    public WrappedDialog create(Player player, KeyItemDialogContext context) {
        ItemStack itemStack = context.itemStack();

        List<WrappedDialogInput> inputs = new ArrayList<>();

        boolean isVanillaOnly = ItemHelper.isBukkitOnly(itemStack);
        boolean isMixedItem = ItemHelper.isMixed(itemStack);
        boolean preferNBT = isMixedItem || isVanillaOnly;

        AdaptedItem adaptedItem = ItemHelper.bukkitIfFromCrates(itemStack);
        ItemProvider provider = ItemBridge.get().getProvider(itemStack);

        PlaceholderContext placeholders = PlaceholderContext.builder()
            .with(SharedPlaceholders.TYPE, () -> provider == null ? "null" : provider.getId())
            .build();

        if (!isVanillaOnly) {
            List<WrappedSingleOptionEntry> methodTypes = new ArrayList<>();

            String refDisplay = placeholders.apply(Lang.GENERIC_UI_DIALOG_ITEM_SAVE_METHOD_ITEM_REF.text());
            String nbtDisplay = Lang.GENERIC_UI_DIALOG_ITEM_SAVE_METHOD_SNBT.text();
            String inputLabel = Lang.GENERIC_UI_DIALOG_ITEM_INPUT_SAVE_METHOD.text();

            methodTypes.add(new WrappedSingleOptionEntry(KEY_USE_REF, refDisplay, !preferNBT));
            methodTypes.add(new WrappedSingleOptionEntry(KEY_USE_NBT, nbtDisplay, preferNBT));

            inputs.add(DialogInputs.singleOption(KEY_SAVE_METHOD, inputLabel, methodTypes).build());
        }

        inputs.add(DialogInputs.bool(KEY_SET_DISPLAY_NAME, KeyItemLang.UI_DIALOG_ITEM_INPUT_SET_DISPLAY_NAME)
            .initial(true)
            .build()
        );

        inputs.add(DialogInputs.bool(KEY_SET_DISPLAY_LORE, KeyItemLang.UI_DIALOG_ITEM_INPUT_SET_DISPLAY_LORE)
            .initial(true)
            .build()
        );

        List<WrappedDialogBody> bodies = new ArrayList<>();
        // Re-adapt custom item for more accurate preview, so if user made any
        // changes to the item after it was generated by its item provider,
        // they can see the "original" output result here.
        bodies.add(DialogBodies.item(isVanillaOnly ? itemStack : ItemHelper.toItemStack(adaptedItem)).build());
        bodies.add(DialogBodies.plain(KeyItemLang.UI_DIALOG_ITEM_BODY_NORMAL).build());

        if (!isVanillaOnly) {
            if (isMixedItem) {
                bodies.add(DialogBodies.plain(Lang.GENERIC_UI_DIALOG_ITEM_BODY_MIXED).build());
            }
            else {
                bodies.add(DialogBodies.plain(Lang.GENERIC_UI_DIALOG_ITEM_BODY_CUSTOM)
                    .placeholders(placeholders)
                    .build()
                );
            }
        }

        return Dialogs.create(builder -> {
            builder.base(DialogBases.builder(KeyItemLang.UI_DIALOG_ITEM_TITLE)
                .body(bodies)
                .inputs(inputs)
                .build());

            builder.type(DialogTypes.confirmation(DialogButtons.apply(), DialogButtons.cancel()));
            builder.handleResponse(DialogActions.APPLY, (viewer, identifier, nbtHolder) -> {
                if (nbtHolder == null) return;

                KeyEditorHook hook = context.hook();

                String saveMethod = nbtHolder.getText(KEY_SAVE_METHOD, KEY_USE_NBT);
                boolean useItemRef = KEY_USE_REF.equalsIgnoreCase(saveMethod);

                boolean setDisplayName = nbtHolder.getBoolean(KEY_SET_DISPLAY_NAME, true);
                boolean setDisplayLore = nbtHolder.getBoolean(KEY_SET_DISPLAY_LORE, true);

                KeyItemSetupContext setupContext = new KeyItemSetupContext(itemStack, useItemRef, setDisplayName,
                    setDisplayLore);
                this.controller.onItemStackDialogSubmit(player, hook, setupContext);

                viewer.callback();
            });
        });
    }
}
