package su.nightexpress.excellentcrates.reward.editor.ui.dialog;

import java.util.ArrayList;
import java.util.List;

import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.jspecify.annotations.NullMarked;

import su.nightexpress.excellentcrates.api.crate.Crate;
import su.nightexpress.excellentcrates.core.SharedConstants;
import su.nightexpress.excellentcrates.core.SharedPlaceholders;
import su.nightexpress.excellentcrates.core.lang.Lang;
import su.nightexpress.excellentcrates.reward.editor.context.RewardCreationContext;
import su.nightexpress.excellentcrates.reward.editor.lang.RewardEditorLang;
import su.nightexpress.excellentcrates.reward.editor.ui.RewardEditorUIController;
import su.nightexpress.excellentcrates.reward.editor.ui.dialog.context.RewardManualCreationDialogContext;
import su.nightexpress.excellentcrates.util.ItemHelper;
import su.nightexpress.nightcore.bridge.dialog.wrap.WrappedDialog;
import su.nightexpress.nightcore.bridge.dialog.wrap.body.WrappedDialogBody;
import su.nightexpress.nightcore.bridge.dialog.wrap.input.WrappedDialogInput;
import su.nightexpress.nightcore.bridge.dialog.wrap.input.single.WrappedSingleOptionEntry;
import su.nightexpress.nightcore.bridge.item.AdaptedItem;
import su.nightexpress.nightcore.integration.item.ItemBridge;
import su.nightexpress.nightcore.integration.item.ItemProvider;
import su.nightexpress.nightcore.ui.dialog.Dialogs;
import su.nightexpress.nightcore.ui.dialog.build.DialogActions;
import su.nightexpress.nightcore.ui.dialog.build.DialogBases;
import su.nightexpress.nightcore.ui.dialog.build.DialogBodies;
import su.nightexpress.nightcore.ui.dialog.build.DialogButtons;
import su.nightexpress.nightcore.ui.dialog.build.DialogInputs;
import su.nightexpress.nightcore.ui.dialog.build.DialogTypes;
import su.nightexpress.nightcore.ui.dialog.wrap.Dialog;
import su.nightexpress.nightcore.util.placeholder.PlaceholderContext;

@NullMarked
public class RewardManualCreationDialog extends Dialog<RewardManualCreationDialogContext> {

    private static final String KEY_USE_REF            = "use_ref";
    private static final String KEY_USE_NBT            = "use_nbt";
    private static final String KEY_SAVE_METHOD        = "save_method";
    private static final String KEY_REWARD_ID          = "reward_id";
    private static final String KEY_ADD_TO_GIVEN_ITEMS = "add_to_given_items";

    private final RewardEditorUIController controller;

    public RewardManualCreationDialog(RewardEditorUIController controller) {
        super();
        this.controller = controller;
    }

    @Override
    public WrappedDialog create(Player player, RewardManualCreationDialogContext context) {
        ItemStack itemStack = context.item();
        String name = context.name();

        List<WrappedDialogInput> inputs = new ArrayList<>();

        boolean isVanillaOnly = ItemHelper.isBukkitOnly(itemStack);
        boolean isMixedItem = ItemHelper.isMixed(itemStack);
        boolean preferNBT = isMixedItem || isVanillaOnly;

        AdaptedItem adaptedItem = ItemHelper.bukkitIfFromCrates(itemStack);
        ItemProvider provider = ItemBridge.get().getProvider(itemStack);

        PlaceholderContext placeholders = PlaceholderContext.builder()
            .with(SharedPlaceholders.TYPE, () -> provider == null ? "null" : provider.getId())
            .build();

        if (!isVanillaOnly) {
            List<WrappedSingleOptionEntry> methodTypes = new ArrayList<>();

            String refDisplay = placeholders.apply(Lang.GENERIC_UI_DIALOG_ITEM_SAVE_METHOD_ITEM_REF.text());
            String nbtDisplay = Lang.GENERIC_UI_DIALOG_ITEM_SAVE_METHOD_SNBT.text();
            String inputLabel = Lang.GENERIC_UI_DIALOG_ITEM_INPUT_SAVE_METHOD.text();

            methodTypes.add(new WrappedSingleOptionEntry(KEY_USE_REF, refDisplay, !preferNBT));
            methodTypes.add(new WrappedSingleOptionEntry(KEY_USE_NBT, nbtDisplay, preferNBT));

            inputs.add(DialogInputs.singleOption(KEY_SAVE_METHOD, inputLabel, methodTypes).build());
        }

        inputs.add(DialogInputs.text(KEY_REWARD_ID, RewardEditorLang.UI_DIALOG_MANUAL_CREATION_INPUT_ID)
            .initial(name == null ? "" : name)
            .maxLength(SharedConstants.MAX_REWARD_ID_LENGTH)
            .width(250)
            .build()
        );

        inputs.add(DialogInputs.bool(KEY_ADD_TO_GIVEN_ITEMS,
            RewardEditorLang.UI_DIALOG_MANUAL_CREATION_INPUT_ADD_TO_GIVEN_ITEMS)
            .initial(true)
            .build()
        );

        List<WrappedDialogBody> bodies = new ArrayList<>();
        // Re-adapt custom item for more accurate preview, so if user made any
        // changes to the item after it was generated by its item provider,
        // they can see the "original" output result here.
        bodies.add(DialogBodies.item(isVanillaOnly ? itemStack : ItemHelper.toItemStack(adaptedItem)).build());
        bodies.add(DialogBodies.plain(RewardEditorLang.UI_DIALOG_MANUAL_CREATION_BODY).build());

        if (!isVanillaOnly) {
            if (isMixedItem) {
                bodies.add(DialogBodies.plain(Lang.GENERIC_UI_DIALOG_ITEM_BODY_MIXED).build());
            }
            else {
                bodies.add(DialogBodies.plain(Lang.GENERIC_UI_DIALOG_ITEM_BODY_CUSTOM)
                    .placeholders(placeholders)
                    .build()
                );
            }
        }

        return Dialogs.create(builder -> {
            builder.base(DialogBases.builder(RewardEditorLang.UI_DIALOG_MANUAL_CREATION_TITLE)
                .body(bodies)
                .inputs(inputs)
                .build());

            builder.type(DialogTypes.confirmation(DialogButtons.apply(), DialogButtons.cancel()));
            builder.handleResponse(DialogActions.APPLY, (viewer, identifier, nbtHolder) -> {
                if (nbtHolder == null) return;

                Crate crate = context.crateRef().get();
                if (crate == null) return;

                Player clicker = viewer.getPlayer();

                String saveMethod = nbtHolder.getText(KEY_SAVE_METHOD, KEY_USE_NBT);
                boolean useItemRef = KEY_USE_REF.equalsIgnoreCase(saveMethod);

                String id = nbtHolder.getText(KEY_REWARD_ID, "");
                boolean addToGivenItems = nbtHolder.getBoolean(KEY_ADD_TO_GIVEN_ITEMS, true);

                RewardCreationContext result = new RewardCreationContext(itemStack, useItemRef, addToGivenItems);
                this.controller.onManualCreationDialogSubmit(clicker, crate, id, context.hook(), result);

                viewer.closeFully();
            });
        });
    }
}
