package su.nightexpress.excellentcrates.reward.editor.ui.dialog;

import java.util.ArrayList;
import java.util.List;

import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.jspecify.annotations.NullMarked;

import su.nightexpress.excellentcrates.core.SharedPlaceholders;
import su.nightexpress.excellentcrates.core.lang.Lang;
import su.nightexpress.excellentcrates.reward.RewardsConstants;
import su.nightexpress.excellentcrates.reward.editor.context.RewardCreateContext;
import su.nightexpress.excellentcrates.reward.editor.context.RewardCreateInputContext;
import su.nightexpress.excellentcrates.reward.editor.lang.RewardEditorLang;
import su.nightexpress.excellentcrates.reward.editor.ui.RewardEditorUIController;
import su.nightexpress.excellentcrates.util.ItemHelper;
import su.nightexpress.nightcore.bridge.dialog.wrap.WrappedDialog;
import su.nightexpress.nightcore.bridge.dialog.wrap.body.WrappedDialogBody;
import su.nightexpress.nightcore.bridge.dialog.wrap.input.WrappedDialogInput;
import su.nightexpress.nightcore.bridge.dialog.wrap.input.single.WrappedSingleOptionEntry;
import su.nightexpress.nightcore.bridge.item.AdaptedItem;
import su.nightexpress.nightcore.ui.dialog.Dialogs;
import su.nightexpress.nightcore.ui.dialog.build.DialogActions;
import su.nightexpress.nightcore.ui.dialog.build.DialogBases;
import su.nightexpress.nightcore.ui.dialog.build.DialogBodies;
import su.nightexpress.nightcore.ui.dialog.build.DialogButtons;
import su.nightexpress.nightcore.ui.dialog.build.DialogInputs;
import su.nightexpress.nightcore.ui.dialog.build.DialogTypes;
import su.nightexpress.nightcore.ui.dialog.wrap.Dialog;
import su.nightexpress.nightcore.util.placeholder.PlaceholderContext;

@NullMarked
public class RewardCreationDialog extends Dialog<RewardCreateContext> {

    private static final String JSON_USE_REF     = "use_ref";
    private static final String JSON_USE_NBT     = "use_nbt";
    private static final String JSON_SAVE_METHOD = "save_method";
    private static final String JSON_REWARD_ID   = "reward_id";
    private static final String JSON_SET_ITEM    = "set_item";

    private final RewardEditorUIController controller;

    public RewardCreationDialog(RewardEditorUIController controller) {
        super();
        this.controller = controller;
    }

    @Override
    public WrappedDialog create(Player player, RewardCreateContext context) {
        ItemStack itemStack = context.item();
        String name = context.name();

        List<WrappedDialogInput> inputs = new ArrayList<>();

        boolean isVanillaOnly = ItemHelper.isVanillaOnly(itemStack);
        boolean isMixedItem = ItemHelper.isMixedItem(itemStack);
        boolean preferNBT = isMixedItem || isVanillaOnly;

        AdaptedItem adaptedItem = ItemHelper.adapt(itemStack);

        PlaceholderContext placeholders = PlaceholderContext.builder()
            .with(SharedPlaceholders.TYPE, () -> adaptedItem.getAdapter().getName())
            .build();

        if (!isVanillaOnly) {
            List<WrappedSingleOptionEntry> methodTypes = new ArrayList<>();

            String refDisplay = placeholders.apply(Lang.GENERIC_UI_DIALOG_ITEM_SAVE_METHOD_ITEM_REF.text());
            String nbtDisplay = Lang.GENERIC_UI_DIALOG_ITEM_SAVE_METHOD_SNBT.text();
            String inputLabel = Lang.GENERIC_UI_DIALOG_ITEM_INPUT_SAVE_METHOD.text();

            methodTypes.add(new WrappedSingleOptionEntry(JSON_USE_REF, refDisplay, !preferNBT));
            methodTypes.add(new WrappedSingleOptionEntry(JSON_USE_NBT, nbtDisplay, preferNBT));

            inputs.add(DialogInputs.singleOption(JSON_SAVE_METHOD, inputLabel, methodTypes).build());
        }

        inputs.add(DialogInputs.text(JSON_REWARD_ID, RewardEditorLang.UI_DIALOG_CREATION_INPUT_ID)
            .initial(name == null ? "" : name)
            .maxLength(RewardsConstants.REWARD_ID_LENGTH)
            .width(250)
            .build()
        );

        inputs.add(DialogInputs.bool(JSON_SET_ITEM, RewardEditorLang.UI_DIALOG_CREATION_INPUT_ADD_TO_GIVEN_ITEMS)
            .initial(true)
            .build()
        );

        List<WrappedDialogBody> bodies = new ArrayList<>();
        // Re-adapt custom item for more accurate preview, so if user made any
        // changes to the item after it was generated by its item provider,
        // they can see the "original" output result here.
        bodies.add(DialogBodies.item(isVanillaOnly ? itemStack : ItemHelper.toItemStack(adaptedItem)).build());
        bodies.add(DialogBodies.plain(RewardEditorLang.UI_DIALOG_CREATION_BODY).build());

        if (!isVanillaOnly) {
            if (isMixedItem) {
                bodies.add(DialogBodies.plain(Lang.GENERIC_UI_DIALOG_ITEM_BODY_MIXED).build());
            }
            else {
                bodies.add(DialogBodies.plain(Lang.GENERIC_UI_DIALOG_ITEM_BODY_CUSTOM)
                    .placeholders(placeholders)
                    .build()
                );
            }
        }

        return Dialogs.create(builder -> {
            builder.base(DialogBases.builder(RewardEditorLang.UI_DIALOG_CREATION_TITLE)
                .body(bodies)
                .inputs(inputs)
                .build());

            builder.type(DialogTypes.confirmation(DialogButtons.apply(), DialogButtons.cancel()));
            builder.handleResponse(DialogActions.APPLY, (viewer, identifier, nbtHolder) -> {
                if (nbtHolder == null) return;

                String saveMethod = nbtHolder.getText(JSON_SAVE_METHOD, JSON_USE_NBT);
                boolean useItemRef = JSON_USE_REF.equalsIgnoreCase(saveMethod);

                String id = nbtHolder.getText(JSON_REWARD_ID, "");
                boolean setItemContent = nbtHolder.getBoolean(JSON_SET_ITEM, true);

                RewardCreateInputContext creationContext = new RewardCreateInputContext(id, itemStack, useItemRef,
                    setItemContent);
                this.controller.onDialogCreationApplyClick(player, creationContext);

                viewer.closeFully();
            });
        });
    }
}
