package su.nightexpress.excellentcrates.reward.items.editor.ui.dialog;

import java.util.ArrayList;
import java.util.List;

import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.jspecify.annotations.NullMarked;

import su.nightexpress.excellentcrates.api.reward.Reward;
import su.nightexpress.excellentcrates.api.reward.editor.RewardEditorHook;
import su.nightexpress.excellentcrates.core.SharedPlaceholders;
import su.nightexpress.excellentcrates.core.lang.Lang;
import su.nightexpress.excellentcrates.reward.editor.lang.RewardEditorLang;
import su.nightexpress.excellentcrates.reward.items.editor.ui.RewardItemsEditorUIController;
import su.nightexpress.excellentcrates.reward.items.editor.ui.dialog.context.RewardItemAddDialogContext;
import su.nightexpress.excellentcrates.util.ItemHelper;
import su.nightexpress.nightcore.bridge.dialog.wrap.WrappedDialog;
import su.nightexpress.nightcore.bridge.dialog.wrap.body.WrappedDialogBody;
import su.nightexpress.nightcore.bridge.dialog.wrap.input.WrappedDialogInput;
import su.nightexpress.nightcore.bridge.dialog.wrap.input.single.WrappedSingleOptionEntry;
import su.nightexpress.nightcore.bridge.item.AdaptedItem;
import su.nightexpress.nightcore.integration.item.ItemBridge;
import su.nightexpress.nightcore.integration.item.ItemProvider;
import su.nightexpress.nightcore.ui.dialog.Dialogs;
import su.nightexpress.nightcore.ui.dialog.build.DialogActions;
import su.nightexpress.nightcore.ui.dialog.build.DialogBases;
import su.nightexpress.nightcore.ui.dialog.build.DialogBodies;
import su.nightexpress.nightcore.ui.dialog.build.DialogButtons;
import su.nightexpress.nightcore.ui.dialog.build.DialogInputs;
import su.nightexpress.nightcore.ui.dialog.build.DialogTypes;
import su.nightexpress.nightcore.ui.dialog.wrap.Dialog;
import su.nightexpress.nightcore.util.placeholder.PlaceholderContext;

@NullMarked
public class RewardItemAddDialog extends Dialog<RewardItemAddDialogContext> {

    private static final String KEY_USE_REF     = "use_ref";
    private static final String KEY_USE_NBT     = "use_nbt";
    private static final String KEY_SAVE_METHOD = "save_method";

    private final RewardItemsEditorUIController controller;

    public RewardItemAddDialog(RewardItemsEditorUIController controller) {
        super();
        this.controller = controller;
    }

    @Override
    public WrappedDialog create(Player player, RewardItemAddDialogContext context) {
        RewardEditorHook hook = context.hook();
        ItemStack itemStack = context.itemStack();

        List<WrappedDialogInput> inputs = new ArrayList<>();

        boolean isMixedItem = ItemHelper.isMixed(itemStack);
        AdaptedItem adaptedItem = ItemHelper.bukkitIfCrates(itemStack);
        ItemProvider provider = ItemBridge.get().getProvider(itemStack);

        PlaceholderContext placeholders = PlaceholderContext.builder()
            .with(SharedPlaceholders.TYPE, () -> provider == null ? "null" : provider.getId())
            .build();

        List<WrappedSingleOptionEntry> methodTypes = new ArrayList<>();

        String refDisplay = placeholders.apply(Lang.GENERIC_UI_DIALOG_ITEM_SAVE_METHOD_ITEM_REF.text());
        String nbtDisplay = Lang.GENERIC_UI_DIALOG_ITEM_SAVE_METHOD_SNBT.text();
        String inputLabel = Lang.GENERIC_UI_DIALOG_ITEM_INPUT_SAVE_METHOD.text();

        methodTypes.add(new WrappedSingleOptionEntry(KEY_USE_REF, refDisplay, !isMixedItem));
        methodTypes.add(new WrappedSingleOptionEntry(KEY_USE_NBT, nbtDisplay, isMixedItem));

        inputs.add(DialogInputs.singleOption(KEY_SAVE_METHOD, inputLabel, methodTypes).build());

        List<WrappedDialogBody> bodies = new ArrayList<>();

        // Re-adapt custom item for more accurate preview, so if user made any
        // changes to the item after it was generated by its item provider,
        // they can see the "original" output result here.
        bodies.add(DialogBodies.item(ItemHelper.toItemStack(adaptedItem)).build());
        bodies.add(DialogBodies.plain(RewardEditorLang.UI_DIALOG_ITEM_ADD_BODY).build());

        if (isMixedItem) {
            bodies.add(DialogBodies.plain(Lang.GENERIC_UI_DIALOG_ITEM_BODY_MIXED).build());
        }
        else {
            bodies.add(DialogBodies.plain(Lang.GENERIC_UI_DIALOG_ITEM_BODY_CUSTOM)
                .placeholders(placeholders)
                .build()
            );
        }

        return Dialogs.create(builder -> {
            builder.base(DialogBases.builder(RewardEditorLang.UI_DIALOG_ITEM_ADD_TITLE)
                .body(bodies)
                .inputs(inputs)
                .build());

            builder.type(DialogTypes.confirmation(DialogButtons.apply(), DialogButtons.cancel()));
            builder.handleResponse(DialogActions.APPLY, (viewer, identifier, nbtHolder) -> {
                if (nbtHolder == null) return;

                Reward reward = context.rewardRef().get();
                if (reward == null) return;

                String saveMethod = nbtHolder.getText(KEY_SAVE_METHOD, KEY_USE_NBT);
                boolean useItemRef = KEY_USE_REF.equalsIgnoreCase(saveMethod);

                if (this.controller.onDialogItemAddConfirm(player, reward, hook, itemStack, useItemRef)) {
                    viewer.callback();
                }
            });
        });
    }

}
